name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Present Dic
      run: pwd
    - name: List all Files 
      run: ls -lart 
    - name: Parent Dir
      run: ls -lart ../.
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag akash2004u/mediasoup-node:latest
    - name: DockerHub Push
      run: docker push ${{secrets.DOCKER_USERNAME}}/maven-node:latest
